# Generated by Django 2.2 on 2019-04-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20190420_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='type',
        ),
        migrations.AddField(
            model_name='meal',
            name='mealtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealtype_meal', to='generator.MealType'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='mealtype',
            field=models.ManyToManyField(related_name='mealtype_ingreds', to='generator.MealType'),
        ),
    ]
