# Generated by Django 2.2 on 2019-04-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20190420_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['mealtype__ordering']},
        ),
    ]
