# Generated by Django 2.2 on 2019-04-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20190422_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='mealtype',
        ),
    ]
