# Generated by Django 2.2 on 2019-04-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20190422_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='event',
        ),
        migrations.AlterField(
            model_name='meal',
            name='obj_func',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='obj_func'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Occurrence'),
        ),
    ]
