# Generated by Django 2.2 on 2019-05-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20190506_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Benötigte Versuche für Planerstellung pro Tag'),
        ),
        migrations.AddField(
            model_name='person',
            name='generating_time',
            field=models.FloatField(default=0.0, verbose_name='Benötigte Zeit zum Generieren (min)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='activity',
            field=models.CharField(blank=True, choices=[('1', 'Sitzend oder liegend (1)'), ('2', 'Sitzend und leichte Freizeitaktivitäten (2)'), ('3', 'Sitzend, laufend und leichte Freizeitaktivitäten (3)'), ('4', 'Überwiegend stehened und laufend (4)'), ('5', 'Körperlich anstrengende Arbeit und viele Freizeitaktivitäten (5)')], default=2, help_text='Hier gilt folgende Zuordnung: 1: Bettlägerige |\n2: Büroangestellte |\n3: Studenten |\n4: Kellner |\n5: Bauarbeiter', max_length=11, null=True, verbose_name='Aktivitäslevel'),
        ),
        migrations.AlterField(
            model_name='person',
            name='goal',
            field=models.CharField(choices=[('l', 'Gewicht verlieren'), ('g', 'Gewicht zunehmen'), ('k', 'Gewicht halten')], default='k', max_length=11, verbose_name='Ziel'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sports',
            field=models.BooleanField(default=False, help_text='Falls man min. 4-5x die Woche 30-60min Sport macht', verbose_name='Sport oder anstrengende Freizeitaktivitäten'),
        ),
    ]
